# docker-compose.yml
version: "3.8"

services:
  crawler:
    build:
      context: .
      dockerfile: docker/crawler/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./packages/crawler:/app
